# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ToDeOlho' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'FBSDKLoginKit', '~> 4.39.1'
pod 'GoogleSignIn'
pod ‘Alamofire’
pod 'SVProgressHUD'
pod 'CryptoSwift’

 #pod 'TwitterKit'

end
